Route22_TestZone_Text_TestHeptaNoIntro::
    .string "Tyrone: {PLAYER}...\p"
    .string "Estas por presenciar un sustito.\p"
    .string "Algo chiquitico, no tan...\n"
    .string "impresionante.\p"
    .string "Espero estes listo.$"

Route22_TestZone_Text_TestHeptaNoDefeat::
    .string "No... imposible.$"

Route22_TestZone_Text_TestHeptaNoAfter::
    .string "Esto fue solo una prueba.\p"
    .string "Ya veremos qué sigue, espera noticias.$"

Route22_TestZone_Text_TestHeptanoBeaten::
	.string "Jaja, reinicia o crea otro archivo.$"

Route22_TestZone_Text_ObtainedAnHeptaNo::
    .string "{PLAYER} obtained an HEPTANO!$"

Route22_TestZone_Text_ObtainedAnMalwaragon::
    .string "{PLAYER} obtained an MALWARAGON!$"

Route22_TestZone_Text_TestSign::
	.string "Ingresa a la cueva para acceder\n"
	.string "al TestBuild ;)$"

Route22_TestZone_Text_Healer::
    .string "Venga, a curar el equipo$"
